allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-1
  password: amazonskr05
  port: '443'
  server: 54.169.139.18
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-2
  password: amazonskr05
  port: '443'
  server: 47.130.3.54
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-1
  password: amazonskr05
  port: '443'
  server: 54.95.5.168
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-2
  password: amazonskr05
  port: '443'
  server: 52.69.236.102
  tfo: false
  type: ss
- cipher: rc4-md5
  name: ä¸­å›½-1
  obfs: plain
  obfs-param: cd5ed74592.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: '40257'
  protocol: auth_aes128_md5
  protocol-param: 74592:o4fbeopsgcf
  server: 28b09af269781f9b.cdn.jiashule.com
  type: ssr
- cipher: aes-128-gcm
  name: é¦™æ¸¯-1
  password: 26f959e3-1a5e-3b3d-b4cd-fe04c80902bd
  port: '10004'
  server: cdn.node1.lilisi.link
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-3
  password: amazonskr05
  port: '443'
  server: 57.181.42.181
  tfo: false
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-2
  password: bea6b53a-420e-4098-af95-fab651ed6008
  port: '11001'
  server: 183.240.255.75
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-3
  password: amazonskr05
  port: '443'
  server: 13.229.98.87
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-4
  password: amazonskr05
  port: '443'
  server: 47.129.170.82
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-4
  password: amazonskr05
  port: '443'
  server: 13.113.17.246
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-5
  password: amazonskr05
  port: '443'
  server: 13.229.212.209
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-6
  password: amazonskr05
  port: '443'
  server: 52.77.209.61
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-7
  password: amazonskr05
  port: '443'
  server: 13.250.3.43
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-5
  password: amazonskr05
  port: '443'
  server: 54.249.197.65
  tfo: false
  type: ss
- cipher: chacha20-ietf
  name: å¡èˆŒå°”-1
  password: asd123456
  port: '8388'
  server: 154.197.98.64
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-1
  password: qwerREWQ@@
  port: '54345'
  server: 221.139.79.57
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-3
  password: bea6b53a-420e-4098-af95-fab651ed6008
  port: '11001'
  server: 61.172.235.22
  type: ss
- client-fingerprint: chrome
  mptcp: true
  name: ç¾å›½-1
  network: ws
  packet-encoding: xudp
  port: '10086'
  server: 142.147.94.108
  servername: akilelaxub.eessgrgrgrgr.cloudns.nz
  skip-cert-verify: false
  smux:
    enabled: true
    max-streams: '10'
    padding: true
    protocol: h2mux
  tfo: true
  tls: true
  type: vless
  udp: true
  uuid: 2fa6651f-7067-4e5c-a944-f0836d239efd
  ws-opts:
    headers:
      Host: akilelaxub.eessgrgrgrgr.cloudns.nz
    path: /buefubwuefuwefuwffewf
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true
- cipher: aes-128-gcm
  name: æ—¥æœ¬-6
  password: shadowsocks
  port: '443'
  server: 149.22.87.240
  type: ss
- client-fingerprint: chrome
  mptcp: true
  name: ç¾å›½-2
  network: ws
  packet-encoding: xudp
  port: '37049'
  server: 142.147.94.159
  servername: akilelaxub.eessgrgrgrgr.cloudns.nz
  skip-cert-verify: false
  smux:
    enabled: true
    max-streams: '10'
    padding: true
    protocol: h2mux
  tfo: true
  tls: true
  type: vless
  udp: true
  uuid: 2fa6651f-7067-4e5c-a944-f0836d239efd
  ws-opts:
    headers:
      Host: akilelaxub.eessgrgrgrgr.cloudns.nz
    path: /buefubwuefuwefuwffewf
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-8
  password: amazonskr05
  port: '443'
  server: 13.213.30.242
  type: ss
- cipher: rc4-md5
  name: ä¸­å›½-4
  obfs: plain
  obfs-param: 8195986416.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: '40219'
  protocol: auth_aes128_md5
  protocol-param: 86416:SlZFuy
  server: 7438974b54cf5c57.cdn.jiashule.com
  type: ssr
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-9
  password: amazonskr05
  port: '443'
  server: 54.255.237.249
  tfo: false
  type: ss
- name: ç¾å›½-3
  network: ws
  port: '8880'
  server: 104.19.209.229
  type: vless
  udp: true
  uuid: f0d584bc-342f-4443-ba24-79e4d0e504b1
  ws-opts:
    headers:
      Host: late-tooth.granzinhannah.workers.dev
    path: /?ed=2560
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-10
  password: amazonskr05
  port: '443'
  server: 13.215.205.186
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-4
  password: amazonskr05
  port: '443'
  server: 35.88.136.187
  tfo: false
  type: ss
- cipher: aes-128-gcm
  name: ç¾å›½-5
  password: shadowsocks
  port: '443'
  server: 212.102.47.131
  type: ss
- cipher: aes-128-gcm
  name: ç¾å›½-6
  password: shadowsocks
  port: '443'
  server: 156.146.38.168
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-7
  password: amazonskr05
  port: '443'
  server: 18.246.235.247
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-8
  password: amazonskr05
  port: '443'
  server: 52.10.33.211
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-9
  password: amazonskr05
  port: '443'
  server: 35.87.185.248
  type: ss
- delay: '1117'
  name: ç¾å›½-10
  network: ws
  port: '80'
  server: 151.101.3.10
  type: vless
  udp: true
  uuid: cefffd1d-cc58-4560-b4d1-44f1af528f30
  ws-opts:
    headers:
      Host: uni.fi
    path: /?ed=2048
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-11
  password: amazonskr05
  port: '443'
  server: 44.243.115.246
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-12
  password: amazonskr05
  port: '443'
  server: 54.213.247.125
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-13
  password: amazonskr05
  port: '443'
  server: 54.200.148.115
  tfo: false
  type: ss
- name: ç¾å›½-14
  network: ws
  port: '8880'
  server: 104.20.19.168
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: f0d584bc-342f-4443-ba24-79e4d0e504b1
  ws-opts:
    headers:
      Host: late-tooth.granzinhannah.workers.dev
    path: /?ed=2048
- name: ç¾å›½-15
  network: ws
  port: '8880'
  server: 104.20.71.132
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: f0d584bc-342f-4443-ba24-79e4d0e504b1
  ws-opts:
    headers:
      Host: late-tooth.granzinhannah.workers.dev
    path: /Telegram@Linkvws?ed=2560
- cipher: aes-128-gcm
  name: è‹±å›½-1
  password: shadowsocks
  port: '443'
  server: 141.98.101.181
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-11
  password: amazonskr05
  port: '443'
  server: 47.129.50.131
  tfo: false
  type: ss
- country: ğŸ‡®ğŸ‡ªIE
  delay: '1470'
  name: çˆ±å°”å…°-1
  network: tcp
  password: telegram-id-privatevpns
  port: '22222'
  server: 18.203.38.245
  sni: trojan.burgerip.co.uk
  type: trojan
  udp: true
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-16
  password: amazonskr05
  port: '443'
  server: 35.94.16.186
  tfo: false
  type: ss
- cipher: aes-256-gcm
  delay: '1164'
  name: ç¾å›½-17
  password: XKFKl2rULjIp74
  port: '8009'
  server: 38.110.1.105
  type: ss
  udp: true
- cipher: aes-256-gcm
  delay: '1391'
  name: ç¾å›½-18
  password: g5MeD6Ft3CWlJId
  port: '5004'
  server: 38.110.1.105
  type: ss
  udp: true
- name: éŸ©å›½-2
  network: tcp
  password: 64f33df2-4f9d-4cf3-bb69-b82b08cf149a
  port: '20985'
  server: ent1.imyourdaddy.top
  skip-cert-verify: true
  sni: sale.alibaba.com
  type: trojan
  udp: true
- cipher: aes-256-gcm
  name: ç¾å›½-19
  password: g5MeD6Ft3CWlJId
  port: '5003'
  server: 38.110.1.105
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-20
  password: KixLvKzwjekG00rm
  port: '8000'
  server: 38.110.1.105
  type: ss
- cipher: aes-256-gcm
  delay: '1870'
  name: ç¾å›½-21
  password: Y6R9pAtvxxzmGC
  port: '9090'
  server: 38.110.1.105
  type: ss
  udp: true
- cipher: aes-256-gcm
  delay: '978'
  name: ç¾å›½-22
  password: KixLvKzwjekG00rm
  port: '8080'
  server: 38.110.1.105
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: ç¾å›½-23
  password: pKEW8JPByTVTLtM
  port: '443'
  server: 38.110.1.105
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-24
  password: Y6R9pAtvxxzmGC
  port: '5001'
  server: 38.114.114.69
  type: ss
- client-fingerprint: chrome
  delay: '884'
  name: ç¾å›½-25
  network: ws
  port: '443'
  server: 199.232.5.79
  servername: mefa.ir
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: mefa.ir
    path: /H?ed=2560
- cipher: aes-256-gcm
  name: ç¾å›½-26
  password: cdBIDV42DCwnfIN
  port: '8118'
  server: 38.110.1.105
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-27
  password: e4FCWrgpkji3QY
  port: '9101'
  server: 38.110.1.105
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-28
  password: lGqs95QkFHo2NV
  port: '5498'
  server: 38.110.1.105
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-29
  password: cdBIDV42DCwnfIN
  port: '8119'
  server: 38.110.1.105
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-30
  password: zDNVedRFPQexG9v
  port: '6379'
  server: 38.114.114.69
  type: ss
- cipher: aes-256-gcm
  name: æ³•å›½-1
  password: KixLvKzwjekG00rm
  port: '8080'
  server: 54.37.12.219
  type: ss
- alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: ç¾å›½-31
  network: ws
  port: '443'
  server: 199.232.5.101
  servername: mefa.ir
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: mefa.ir
    path: /H?ed=2560
- cipher: chacha20-ietf-poly1305
  name: èŠ¬å…°-1
  password: X7eoEBrARWsBUiVfchVEdH
  port: '443'
  server: 185.77.217.121
  type: ss
- name: ç¾å›½-32
  network: ws
  port: '80'
  server: 199.232.37.15
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: é»˜è®¤ä»£ç†
  proxies:
  - 'è‡ªåŠ¨é€‰æ‹©: 61ä¸ª'
  - 'æ‰‹åŠ¨é€‰æ‹©: 61ä¸ª'
  - 'æ–°åŠ å¡åˆ†åŒº: 11ä¸ª'
  - 'æ—¥æœ¬åˆ†åŒº: 6ä¸ª'
  - 'ä¸­å›½åˆ†åŒº: 4ä¸ª'
  - 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  - 'å¡èˆŒå°”åˆ†åŒº: 1ä¸ª'
  - 'éŸ©å›½åˆ†åŒº: 2ä¸ª'
  - 'ç¾å›½åˆ†åŒº: 32ä¸ª'
  - 'è‹±å›½åˆ†åŒº: 1ä¸ª'
  - 'çˆ±å°”å…°åˆ†åŒº: 1ä¸ª'
  - 'æ³•å›½åˆ†åŒº: 1ä¸ª'
  - 'èŠ¬å…°åˆ†åŒº: 1ä¸ª'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©: 61ä¸ª'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: 'æ‰‹åŠ¨é€‰æ‹©: 61ä¸ª'
  type: select
- filter: (?i)æ–°åŠ å¡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ–°åŠ å¡åˆ†åŒº: 11ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ—¥æœ¬|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ—¥æœ¬åˆ†åŒº: 6ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ä¸­å›½|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ä¸­å›½åˆ†åŒº: 4ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)é¦™æ¸¯|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)å¡èˆŒå°”|SC|sc
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sc.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'å¡èˆŒå°”åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)éŸ©å›½|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'éŸ©å›½åˆ†åŒº: 2ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç¾å›½|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç¾å›½åˆ†åŒº: 32ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)è‹±å›½|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‹±å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)çˆ±å°”å…°|IE|ie
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ie.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'çˆ±å°”å…°åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ³•å›½|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ³•å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)èŠ¬å…°|FI|fi
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fi.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'èŠ¬å…°åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,é»˜è®¤ä»£ç†
- GEOSITE,microsoft,DIRECT
- GEOIP,google,é»˜è®¤ä»£ç†
- GEOIP,telegram,é»˜è®¤ä»£ç†
- GEOIP,twitter,é»˜è®¤ä»£ç†
- GEOIP,CN,DIRECT,no-resolve
- MATCH,é»˜è®¤ä»£ç†
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
