allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-1
  password: amazonskr05
  port: '443'
  server: 54.250.103.70
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-2
  password: amazonskr05
  port: '443'
  server: 54.249.192.248
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-1
  password: amazonskr05
  port: '443'
  server: 13.250.59.97
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-3
  password: amazonskr05
  port: '443'
  server: 13.114.140.218
  type: ss
- name: ä¸­å›½-1
  password: wwTIozXY
  port: '27131'
  server: 36.151.192.201
  skip-cert-verify: true
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-2
  password: 5409bf78-b122-4b9b-9050-da36576f5bbc
  port: '34676'
  server: tg_mfbpn03.52cloud.us.kg
  type: ss
- name: ä¸­å›½-3
  password: 8d4a8689-e8fd-4405-9834-3f812c528db0
  port: '13035'
  server: naiu-other.05vr9nyqg5.download
  skip-cert-verify: false
  sni: cloudflare.node-ssl.cdn-alibaba.com
  type: trojan
- name: æ—¥æœ¬-4
  network: tcp
  password: 2aa1581d-bfc9-4d3a-84f3-742674fb5d3a
  port: '20230'
  server: jp006.421421.xyz
  skip-cert-verify: true
  sni: 421421.xyz
  type: trojan
  udp: true
- cipher: aes-256-cfb
  name: ä¸­å›½-4
  password: 75ly0yJ90LP5Ural
  port: '20705'
  server: 221.181.185.71
  type: ss
- name: æ—¥æœ¬-5
  network: tcp
  password: 2aa1581d-bfc9-4d3a-84f3-742674fb5d3a
  port: '20230'
  server: jp005.421421.xyz
  skip-cert-verify: true
  sni: 421421.xyz
  type: trojan
  udp: true
- cipher: aes-128-gcm
  name: ä¸­å›½-5
  password: a77f18ea-c88a-402c-85e9-27e1dafbc900
  port: '34702'
  server: 34702.crelay.org
  type: ss
- cipher: aes-128-gcm
  client-fingerprint: chrome
  name: è‹±å›½-1
  password: shadowsocks
  port: '443'
  server: 212.102.53.198
  tfo: false
  type: ss
- cipher: aes-256-cfb
  country: ğŸ‡­ğŸ‡° HK
  delay: '2996'
  name: é¦™æ¸¯-1
  obfs: tls1.2_ticket_auth
  password: iFqnzSscN
  port: '8083'
  protocol: origin
  server: 150.107.46.21
  type: ssr
- cipher: aes-256-cfb
  name: éŸ©å›½-1
  password: amazonskr05
  port: '443'
  server: 43.201.61.86
  type: ss
- cipher: aes-256-cfb
  country: ğŸ‡°ğŸ‡·KR
  delay: '1215'
  name: éŸ©å›½-2
  password: qwerREWQ@@
  port: '54345'
  server: 221.139.79.57
  type: ss
- cipher: chacha20-ietf-poly1305
  name: éŸ©å›½-3
  password: 2155145a-b1b5-443a-8977-670f6bd10f02
  port: '50001'
  server: bgroup.node2.s.nodelist-airport.com
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-4
  password: amazonskr05
  port: '443'
  server: 3.38.253.126
  type: ss
- cipher: chacha20-ietf-poly1305
  client-fingerprint: chrome
  name: ä¸­å›½-6
  password: 69b103f6-2db0-452b-999e-06cb77b8021b
  port: '40018'
  server: hzhz2.sssyun.xyz
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: ä¸­å›½-7
  password: 2LF2EhWMqnlf0kRi
  port: '23961'
  server: 221.181.185.71
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-1
  password: amazonskr05
  port: '443'
  server: 18.236.95.86
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-2
  password: amazonskr05
  port: '443'
  server: 52.43.33.6
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-8
  password: 68a1de21-c639-47c7-9e3c-4dc8a0b14e9f
  port: '35853'
  server: uslow.papermsg.top
  type: ss
- name: éŸ©å›½-5
  network: ws
  port: '443'
  server: 59.3.3.161
  servername: an.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      host: an.ylks.xyz
    path: /blue
- cipher: aes-256-cfb
  name: ç¾å›½-3
  password: amazonskr05
  port: '443'
  server: 54.185.199.99
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-6
  password: amazonskr05
  port: '443'
  server: 3.38.102.189
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-4
  password: 5cp9Z3iWnJZ2
  port: '443'
  server: 205.134.180.150
  type: ss
- name: æ—¥æœ¬-6
  network: ws
  port: '443'
  server: 150.230.196.248
  servername: ln.ylks01.eu.org
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: ln.ylks01.eu.org
    path: /blue
- name: ç¾å›½-5
  network: ws
  port: '443'
  server: 192.9.157.76
  servername: an.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      host: an.ylks.xyz
    path: /?ed=2048
- cipher: chacha20-ietf-poly1305
  name: è‹±å›½-2
  password: mps3FwmDjLrWaOVg
  port: '443'
  server: series-a2.varzesh360.co
  type: ss
- name: ç¾å›½-6
  network: ws
  port: '443'
  server: 150.230.34.116
  servername: an.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      host: an.ylks.xyz
    path: /?ed=2048
- name: ç¾å›½-7
  network: ws
  port: '2082'
  server: 172.67.153.74
  servername: node.vauth.workers.dev
  tls: false
  type: vless
  uuid: 0ebb1677-4902-476f-bc03-3e8c7ca6fd21
  ws-opts:
    headers:
      Host: node.vauth.workers.dev
    path: /?ed=2048
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-8
  password: Oh220yTCQwMCN7Cc7DVlwW
  port: '8985'
  server: 80.92.205.32
  type: ss
- cipher: aes-256-cfb
  name: ä¸­å›½-9
  password: f52SZksXnGNfc72Q
  port: '23382'
  server: 221.181.185.71
  type: ss
- client-fingerprint: chrome
  delay: '2754'
  flow: xtls-rprx-vision
  name: éŸ©å›½-7
  network: tcp
  port: '443'
  reality-opts:
    public-key: t_MDb0CgA1ZwyIj7NpJ2hvp85C9sH8Nsnd8etE8NKw4
  server: 140.238.18.228
  servername: updates.cdn-apple.com
  tls: true
  type: vless
  udp: true
  uuid: 2353e75d-7cec-4e7f-9eae-e996117cac04
- name: éŸ©å›½-8
  network: ws
  port: '443'
  server: 152.70.249.67
  servername: dn.ylks.xyz
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: dn.ylks.xyz
    path: /blue
- name: éŸ©å›½-9
  network: ws
  port: '32900'
  server: 146.56.151.254
  servername: cn.ylks.xyz
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: cn.ylks.xyz
    path: /blue
- client-fingerprint: chrome
  name: ç¾å›½-9
  network: ws
  port: '80'
  server: 104.21.234.71
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.us.fxxk.dedyn.io
- client-fingerprint: chrome
  name: ç¾å›½-10
  network: ws
  port: '80'
  server: 104.17.70.154
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.us.fxxk.dedyn.io
- client-fingerprint: chrome
  name: ç¾å›½-11
  network: ws
  port: '80'
  server: 104.19.240.243
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.oracle.fxxk.dedyn.io
- client-fingerprint: chrome
  name: ç¾å›½-12
  network: ws
  port: '80'
  server: www.wto.org
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.oracle.fxxk.dedyn.io
- client-fingerprint: chrome
  name: ç¾å›½-13
  network: ws
  port: '80'
  server: 104.18.126.133
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.us.fxxk.dedyn.io
- client-fingerprint: chrome
  name: ç¾å›½-14
  network: ws
  port: '80'
  server: cfip.xxxxxxxx.tk
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.oracle.fxxk.dedyn.io
- name: ç¾å›½-15
  network: ws
  port: '8443'
  server: www.wto.org
  servername: ll.ylks.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      Host: ll.ylks.us.kg
    path: /?ed=2560
- client-fingerprint: chrome
  name: ç¾å›½-16
  network: ws
  port: '80'
  server: 104.18.122.90
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.us.fxxk.dedyn.io
- client-fingerprint: chrome
  name: ç¾å›½-17
  network: ws
  port: '80'
  server: bestcf.onecf.eu.org
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 113dd109-540e-4497-9d47-eed30315260f
  ws-opts:
    headers:
      Host: edgetunnel.2424014450.workers.dev
    path: /proxyIP=proxyip.oracle.fxxk.dedyn.io
- cipher: chacha20-ietf-poly1305
  name: è¥¿ç­ç‰™-1
  password: xDYIKyk2KozqAVUHV7CylP
  port: '40076'
  server: 194.87.45.189
  type: ss
- name: ç¾å›½-18
  network: ws
  port: '2087'
  server: ln.ylks.xyz
  servername: ln.ylKS.XYZ
  tls: true
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      host: ln.ylKS.XYZ
    path: /yjxujdbfwclvspf8?ed=2560
- name: ç¾å›½-19
  network: ws
  port: '80'
  server: 104.21.18.154
  servername: server3.mobileberooz-e41.workers.dev
  tls: false
  type: vless
  uuid: 0c1823f5-e8b1-4cfe-8f8b-441f8dd42fd2
  ws-opts:
    headers:
      host: server3.mobileberooz-e41.workers.dev
    path: Twitterè‹å°æŸ 
- cipher: aes-256-cfb
  name: æ³¢å…°-1
  password: UTJA57ypk2XKQpnm
  port: '9033'
  server: 217.30.10.18
  type: ss
- name: ç¾å›½-20
  network: ws
  port: '443'
  server: 43.153.103.203
  servername: dn.ylks.xyz
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: dn.ylks.xyz
    path: /blue
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: é»˜è®¤ä»£ç†
  proxies:
  - 'è‡ªåŠ¨é€‰æ‹©: 50ä¸ª'
  - 'æ‰‹åŠ¨é€‰æ‹©: 50ä¸ª'
  - 'æ—¥æœ¬åˆ†åŒº: 6ä¸ª'
  - 'æ–°åŠ å¡åˆ†åŒº: 1ä¸ª'
  - 'ä¸­å›½åˆ†åŒº: 9ä¸ª'
  - 'è‹±å›½åˆ†åŒº: 2ä¸ª'
  - 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  - 'éŸ©å›½åˆ†åŒº: 9ä¸ª'
  - 'ç¾å›½åˆ†åŒº: 20ä¸ª'
  - 'è¥¿ç­ç‰™åˆ†åŒº: 1ä¸ª'
  - 'æ³¢å…°åˆ†åŒº: 1ä¸ª'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©: 50ä¸ª'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: 'æ‰‹åŠ¨é€‰æ‹©: 50ä¸ª'
  type: select
- filter: (?i)æ—¥æœ¬|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ—¥æœ¬åˆ†åŒº: 6ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ–°åŠ å¡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ–°åŠ å¡åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ä¸­å›½|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ä¸­å›½åˆ†åŒº: 9ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)è‹±å›½|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‹±å›½åˆ†åŒº: 2ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)é¦™æ¸¯|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)éŸ©å›½|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'éŸ©å›½åˆ†åŒº: 9ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç¾å›½|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç¾å›½åˆ†åŒº: 20ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)è¥¿ç­ç‰™|ES|es
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/es.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è¥¿ç­ç‰™åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ³¢å…°|PL|pl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pl.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ³¢å…°åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,é»˜è®¤ä»£ç†
- GEOSITE,microsoft,DIRECT
- GEOIP,google,é»˜è®¤ä»£ç†
- GEOIP,telegram,é»˜è®¤ä»£ç†
- GEOIP,twitter,é»˜è®¤ä»£ç†
- GEOIP,CN,DIRECT,no-resolve
- MATCH,é»˜è®¤ä»£ç†
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
