allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-1
  password: amazonskr05
  port: '443'
  server: 54.251.68.99
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-2
  password: amazonskr05
  port: '443'
  server: 52.221.248.211
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-3
  password: amazonskr05
  port: '443'
  server: 47.128.225.94
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-1
  password: amazonskr05
  port: '443'
  server: 54.248.142.136
  tfo: false
  type: ss
- name: ä¸­å›½-1
  password: QwwHvrnN
  port: '25241'
  server: 36.151.192.196
  skip-cert-verify: true
  type: trojan
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-4
  password: amazonskr05
  port: '443'
  server: 18.141.184.102
  tfo: false
  type: ss
- name: æ—¥æœ¬-2
  network: tcp
  password: d971ee7a-32d9-402a-8a4f-d2135d48a47b
  port: '20230'
  server: jp005.421421.xyz
  skip-cert-verify: true
  sni: 421421.xyz
  type: trojan
  udp: true
- alpn:
  - h3
  congestion-controller: bbr
  name: ç¾å›½-1
  password: d07a5927-3ed1-4a1a-b9fa-799e7d09a8e9
  port: '16002'
  server: vr.179179.xyz
  type: tuic
  uuid: d07a5927-3ed1-4a1a-b9fa-799e7d09a8e9
- alpn:
  - h3
  name: ç¾å›½-2
  password: d07a5927-3ed1-4a1a-b9fa-799e7d09a8e9
  port: '12959'
  server: vr.179179.xyz
  skip-cert-verify: false
  sni: vr.179179.xyz
  type: hysteria2
- alpn:
  - h3
  name: ç¾å›½-3
  password: 5aa778a9-1789-4d2f-b4bb-f182d2b63f57
  port: '29800'
  server: hy.179179.xyz
  skip-cert-verify: false
  sni: hy.179179.xyz
  type: hysteria2
- name: é¦™æ¸¯-1
  port: '4000'
  server: hk9.ftq.ink
  tls: true
  type: http
- alpn:
  - h3
  congestion-controller: bbr
  name: ç¾å›½-4
  password: 341ed386-38cc-412c-a3c9-bbff24b22ed4
  port: '42189'
  server: hy.179179.xyz
  type: tuic
  uuid: 341ed386-38cc-412c-a3c9-bbff24b22ed4
- name: ä¸­å›½-2
  password: 5e2ce79c-170e-484a-8802-40584a1a3a12
  port: '13007'
  server: naiu-hk.05vr9nyqg5.download
  skip-cert-verify: false
  sni: cloudflare.node-ssl.cdn-alibaba.com
  type: trojan
- name: æ–°åŠ å¡-5
  network: tcp
  password: d971ee7a-32d9-402a-8a4f-d2135d48a47b
  port: '20230'
  server: sg008.421421.xyz
  skip-cert-verify: true
  sni: 421421.xyz
  type: trojan
  udp: true
- cipher: chacha20-ietf-poly1305
  name: é¦™æ¸¯-2
  password: e7623dcf-82db-4b5c-89e4-3885fc4c3d86
  port: '50006'
  server: iepl2.forlive.live
  type: ss
- cipher: rc4-md5
  country: ğŸ‡¨ğŸ‡³CN
  delay: '618'
  group: SSRProvider
  name: ä¸­å›½-3
  obfs: plain
  obfs-param: 8195986416.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: '40218'
  protocol: auth_aes128_md5
  protocol-param: 86416:SlZFuy
  server: 7438974b54cf5c57.cdn.jiashule.com
  type: ssr
- name: é¦™æ¸¯-3
  password: e87e2257-e387-4254-9b12-ba499549c847
  port: '46983'
  server: 32c7696277e1e7bc6135ffa96da09122.v1.cac.node-is.green
  skip-cert-verify: true
  sni: hk12.bilibili.com
  type: trojan
  udp: true
- cipher: aes-256-cfb
  name: ç¾å›½-5
  password: amazonskr05
  port: '443'
  server: 18.236.89.178
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-6
  password: amazonskr05
  port: '443'
  server: 54.200.220.184
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-7
  password: amazonskr05
  port: '443'
  server: 54.184.77.199
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-8
  password: amazonskr05
  port: '443'
  server: 34.215.84.62
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-9
  password: amazonskr05
  port: '443'
  server: 52.11.76.208
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-10
  password: amazonskr05
  port: '443'
  server: 34.208.196.91
  type: ss
- name: ä¸­å›½-4
  password: DNUMdmnJ
  port: '51377'
  server: 36.151.192.242
  skip-cert-verify: true
  type: trojan
- name: ä¸­å›½-5
  network: tcp
  password: QwwHvrnN
  port: '34185'
  server: 36.151.192.201
  skip-cert-verify: true
  type: trojan
  udp: true
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-11
  password: amazonskr05
  port: '443'
  server: 34.219.118.99
  tfo: false
  type: ss
- name: é¦™æ¸¯-4
  password: e87e2257-e387-4254-9b12-ba499549c847
  port: '43767'
  server: e20d1e7a57a3a891866d828966cede06.v1.cac.node-is.green
  skip-cert-verify: true
  sni: jp12.bilibili.com
  type: trojan
  udp: true
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-12
  password: amazonskr05
  port: '443'
  server: 34.220.195.209
  tfo: false
  type: ss
- alterId: '0'
  name: å¾·å›½-1
  network: tcp
  password: telegram-id-directvpn
  port: '22222'
  server: 3.120.89.193
  skip-cert-verify: true
  sni: trojan.burgerip.co.uk
  tls: true
  type: trojan
  udp: true
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-13
  password: amazonskr05
  port: '443'
  server: 54.203.119.192
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-14
  password: amazonskr05
  port: '443'
  server: 54.185.18.43
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-15
  password: amazonskr05
  port: '443'
  server: 54.186.178.129
  tfo: false
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-6
  password: amazonskr05
  port: '443'
  server: 54.169.221.192
  tfo: false
  type: ss
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: ç¾å›½-16
  network: tcp
  port: '10003'
  reality-opts:
    public-key: JfDMji8dLkJPhozUtqvh0hL34n5-LQR0Fo1NqNu6uDk
    short-id: 6ba85179e30d4fc2
  server: 142.171.126.130
  servername: www.yzjswz.com
  tls: true
  type: vless
  udp: true
  uuid: 78e31733-b7a2-4e15-8dbf-8c3ebbb07f8d
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: ç¾å›½-17
  password: amazonskr05
  port: '443'
  server: 52.33.189.33
  tfo: false
  type: ss
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: ç¾å›½-18
  network: tcp
  port: '17436'
  reality-opts:
    public-key: 5m86YpAytHADTCSWKlleWGPAp0qq8oFYH_iNu3gtIxA
    short-id: 6ba85179e30d4fc2
  server: 23.105.202.103
  servername: ddyinuo.net
  tls: true
  type: vless
  udp: true
  uuid: 50c74bf0-f502-4d16-af22-f3f13fde82a6
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-7
  password: amazonskr05
  port: '443'
  server: 3.1.195.116
  tfo: false
  type: ss
- cipher: rc4-md5
  group: SSRProvider
  name: æœªçŸ¥-1
  obfs: plain
  obfs-param: 255e7112598.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: '40251'
  protocol: auth_aes128_md5
  protocol-param: 112598:vcy7qi
  server: 95b1cd85a0968ff2.cdn.jiashule.com
  type: ssr
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: é»˜è®¤ä»£ç†
  proxies:
  - 'è‡ªåŠ¨é€‰æ‹©: 38ä¸ª'
  - 'è‡ªåŠ¨é€‰æ‹©(å›½å†…): 9ä¸ª'
  - 'è‡ªåŠ¨é€‰æ‹©(å›½å¤–): 29ä¸ª'
  - 'æ‰‹åŠ¨é€‰æ‹©: 38ä¸ª'
  - 'æ–°åŠ å¡åˆ†åŒº: 7ä¸ª'
  - 'æ—¥æœ¬åˆ†åŒº: 2ä¸ª'
  - 'ä¸­å›½åˆ†åŒº: 5ä¸ª'
  - 'ç¾å›½åˆ†åŒº: 18ä¸ª'
  - 'é¦™æ¸¯åˆ†åŒº: 4ä¸ª'
  - 'å¾·å›½åˆ†åŒº: 1ä¸ª'
  - 'æœªçŸ¥åˆ†åŒº: 1ä¸ª'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©: 38ä¸ª'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©(å›½å†…): 9ä¸ª'
  proxies:
  - ä¸­å›½-1
  - é¦™æ¸¯-1
  - ä¸­å›½-2
  - é¦™æ¸¯-2
  - ä¸­å›½-3
  - é¦™æ¸¯-3
  - ä¸­å›½-4
  - ä¸­å›½-5
  - é¦™æ¸¯-4
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©(å›½å¤–): 29ä¸ª'
  proxies:
  - æ–°åŠ å¡-1
  - æ–°åŠ å¡-2
  - æ–°åŠ å¡-3
  - æ—¥æœ¬-1
  - æ–°åŠ å¡-4
  - æ—¥æœ¬-2
  - ç¾å›½-1
  - ç¾å›½-2
  - ç¾å›½-3
  - ç¾å›½-4
  - æ–°åŠ å¡-5
  - ç¾å›½-5
  - ç¾å›½-6
  - ç¾å›½-7
  - ç¾å›½-8
  - ç¾å›½-9
  - ç¾å›½-10
  - ç¾å›½-11
  - ç¾å›½-12
  - å¾·å›½-1
  - ç¾å›½-13
  - ç¾å›½-14
  - ç¾å›½-15
  - æ–°åŠ å¡-6
  - ç¾å›½-16
  - ç¾å›½-17
  - ç¾å›½-18
  - æ–°åŠ å¡-7
  - æœªçŸ¥-1
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: 'æ‰‹åŠ¨é€‰æ‹©: 38ä¸ª'
  type: select
- filter: (?i)æ–°åŠ å¡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ–°åŠ å¡åˆ†åŒº: 7ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ—¥æœ¬|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ—¥æœ¬åˆ†åŒº: 2ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ä¸­å›½|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ä¸­å›½åˆ†åŒº: 5ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç¾å›½|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç¾å›½åˆ†åŒº: 18ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)é¦™æ¸¯|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'é¦™æ¸¯åˆ†åŒº: 4ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)å¾·å›½|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'å¾·å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æœªçŸ¥|cn|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æœªçŸ¥åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,é»˜è®¤ä»£ç†
- DOMAIN,cdn.usefathom.com,é»˜è®¤ä»£ç†
- GEOSITE,anthropic,é»˜è®¤ä»£ç†
- GEOSITE,microsoft,DIRECT
- GEOIP,google,é»˜è®¤ä»£ç†
- GEOIP,telegram,é»˜è®¤ä»£ç†
- GEOIP,twitter,é»˜è®¤ä»£ç†
- GEOIP,CN,DIRECT,no-resolve
- MATCH,é»˜è®¤ä»£ç†
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
