allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-256-cfb
  name: æ—¥æœ¬-1
  password: amazonskr05
  port: '443'
  server: 54.249.192.248
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-2
  password: amazonskr05
  port: '443'
  server: 13.114.140.218
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-3
  password: amazonskr05
  port: '443'
  server: 54.250.103.70
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-4
  password: amazonskr05
  port: '443'
  server: 43.207.191.29
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-1
  password: amazonskr05
  port: '443'
  server: 13.229.81.137
  type: ss
- name: éŸ©å›½-1
  password: 36146310-e7fc-443f-864c-4fe46b92c35f
  port: '12035'
  server: cn2.cdn.xfltd-cdn.top
  skip-cert-verify: true
  sni: cdn.alibaba.com
  type: trojan
- name: éŸ©å›½-2
  password: 36146310-e7fc-443f-864c-4fe46b92c35f
  port: '12025'
  server: cn2.cdn.xfltd-cdn.top
  skip-cert-verify: true
  sni: cdn.alibaba.com
  type: trojan
- cipher: aes-128-gcm
  name: ä¸­å›½-1
  password: 26f959e3-1a5e-3b3d-b4cd-fe04c80902bd
  port: '10005'
  server: cdn.node1.lilisi.link
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-5
  password: amazonskr05
  port: '443'
  server: 3.113.6.44
  type: ss
- name: ä¸­å›½-2
  password: wwTIozXY
  port: '27131'
  server: 36.151.192.201
  skip-cert-verify: true
  type: trojan
- cipher: aes-256-cfb
  name: ä¸­å›½-3
  password: pyGCMmcxvIGItDqR
  port: '20236'
  server: 221.181.185.71
  type: ss
- cipher: aes-256-cfb
  name: ä¸­å›½-4
  password: 75ly0yJ90LP5Ural
  port: '20705'
  server: 221.181.185.71
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-2
  password: amazonskr05
  port: '443'
  server: 18.142.178.38
  type: ss
- cipher: aes-128-gcm
  client-fingerprint: chrome
  name: ä¸­å›½-5
  password: 26f959e3-1a5e-3b3d-b4cd-fe04c80902bd
  port: '10004'
  server: cdn.node1.lilisi.link
  tfo: false
  type: ss
- cipher: aes-256-gcm
  name: éŸ©å›½-3
  password: 1ijeblXtJy
  port: '21744'
  server: shouer1.209966.xyz
  type: ss
- cipher: aes-128-gcm
  client-fingerprint: chrome
  name: è‹±å›½-1
  password: shadowsocks
  port: '443'
  server: 212.102.53.198
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-4
  password: amazonskr05
  port: '443'
  server: 43.203.254.79
  type: ss
- cipher: aes-256-cfb
  country: ğŸ‡°ğŸ‡·KR
  delay: '386'
  name: éŸ©å›½-5
  password: amazonskr05
  port: '443'
  server: 3.36.61.102
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-6
  password: amazonskr05
  port: '443'
  server: 43.203.197.215
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-6
  password: 5409bf78-b122-4b9b-9050-da36576f5bbc
  port: '42348'
  server: tg_mfbpn03.52cloud.us.kg
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-7
  password: amazonskr05
  port: '443'
  server: 52.78.193.3
  type: ss
- cipher: chacha20-ietf-poly1305
  name: æ³•å›½-1
  password: a8bt9fY0QsLS6eLnXUe0Ym
  port: '8080'
  server: 45.158.171.9
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ä¸­å›½-7
  password: 2e9e4098-4108-4997-94db-552705dbd57a
  port: '29971'
  server: osg020.nod3.org
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-8
  password: amazonskr05
  port: '443'
  server: 3.38.102.189
  type: ss
- cipher: aes-256-cfb
  country: ğŸ‡°ğŸ‡·KR
  delay: '1215'
  name: éŸ©å›½-9
  password: qwerREWQ@@
  port: '54345'
  server: 221.139.79.57
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-1
  password: kDWvXYZoTBcGkC4
  port: '8881'
  server: 139.64.165.154
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-2
  password: e4FCWrgpkji3QY
  port: '9102'
  server: 139.64.165.154
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-3
  password: Y6R9pAtvxxzmGC
  port: '3306'
  server: 139.64.165.154
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-4
  password: amazonskr05
  port: '443'
  server: 54.244.188.170
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-5
  password: Ú¦ÊºlÙ¬TJ1q8DFgÇªÇ¥
  port: '20088'
  server: 67.220.72.41
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-6
  password: KixLvKzwjekG00rm
  port: '5500'
  server: 139.64.165.154
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-7
  password: Ú¦ÊºlÙ¬TJ1q8DFgÇªÇ¥
  port: '20088'
  server: mynode.work.gd
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-8
  password: Y6R9pAtvxxzmGC
  port: '5000'
  server: 139.64.165.154
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-10
  password: amazonskr05
  port: '443'
  server: 3.38.253.126
  type: ss
- alpn:
  - http/1.1
  name: å¾·å›½-1
  network: tcp
  password: telegram-id-directvpn
  port: '22222'
  server: 18.199.207.111
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: è‹±å›½-2
  password: mps3FwmDjLrWaOVg
  port: '443'
  server: series-a2.samanehha.co
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-11
  password: amazonskr05
  port: '443'
  server: 43.201.61.86
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-8
  password: 68a1de21-c639-47c7-9e3c-4dc8a0b14e9f
  port: '35853'
  server: uslow.papermsg.top
  type: ss
- name: ç¾å›½-9
  password: b382cb9d7924e76112ab30ad4e45b430
  port: '38091'
  server: ba3l.thchroute.club
  skip-cert-verify: false
  sni: ba3l.thchroute.club
  type: trojan
- cipher: aes-256-cfb
  name: éŸ©å›½-12
  password: amazonskr05
  port: '443'
  server: 43.202.68.249
  type: ss
- name: è‹±å›½-3
  password: telegram-id-privatevpns
  port: '22222'
  server: 3.9.21.220
  sni: trojan.burgerip.co.uk
  type: trojan
- name: æ³•å›½-2
  password: telegram-id-privatevpns
  port: '22222'
  server: 13.36.87.53
  sni: trojan.burgerip.co.uk
  type: trojan
- name: è‹±å›½-4
  password: telegram-id-privatevpns
  port: '22222'
  server: 3.11.155.109
  sni: trojan.burgerip.co.uk
  type: trojan
- name: è‹±å›½-5
  password: telegram-id-directvpn
  port: '22222'
  server: 18.132.78.2
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-10
  password: Oh220yTCQwMCN7Cc7DVlwW
  port: '8985'
  server: 80.92.205.32
  type: ss
- cipher: chacha20-ietf-poly1305
  client-fingerprint: chrome
  name: ç¾å›½-11
  password: 5cp9Z3iWnJZ2
  port: '443'
  server: 205.134.180.150
  tfo: false
  type: ss
- name: å¾·å›½-2
  password: telegram-id-privatevpns
  port: '22222'
  server: 18.184.141.173
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: aes-256-cfb
  name: ç¾å›½-12
  password: amazonskr05
  port: '443'
  server: 54.185.199.99
  type: ss
- name: ç¾å›½-13
  network: ws
  port: '443'
  server: 198.62.62.156
  servername: lm.ylks.us.kg
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lm.ylks.us.kg
    path: /?ed=2560
- name: æ³•å›½-3
  password: telegram-id-directvpn
  port: '22222'
  server: 13.36.224.254
  sni: trojan.burgerip.co.uk
  type: trojan
- name: çˆ±å°”å…°-1
  password: telegram-id-directvpn
  port: '22222'
  server: 54.74.201.115
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: aes-256-cfb
  name: ç¾å›½-14
  password: amazonskr05
  port: '443'
  server: 35.94.175.12
  type: ss
- name: çˆ±å°”å…°-2
  password: telegram-id-privatevpns
  port: '22222'
  server: 34.241.110.253
  skip-cert-verify: true
  sni: trojan.burgerip.co.uk
  type: trojan
- name: è‹±å›½-6
  password: telegram-id-directvpn
  port: '22222'
  server: 18.170.143.80
  sni: trojan.burgerip.co.uk
  type: trojan
- name: ç‘å…¸-1
  password: telegram-id-directvpn
  port: '22222'
  server: 16.170.186.103
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: chacha20-ietf
  name: æ–°åŠ å¡-3
  password: asd123456
  port: '8388'
  server: 103.36.91.23
  type: ss
- alterId: '0'
  cipher: auto
  client-fingerprint: chrome
  name: ç‘å…¸-2
  password: telegram-id-privatevpns
  port: '22222'
  server: 13.49.130.179
  skip-cert-verify: false
  sni: trojan.burgerip.co.uk
  tfo: false
  tls: false
  type: trojan
  uuid: 83876222-64a4-4912-aa18-b7d9d34959de
- name: ç¾å›½-15
  network: ws
  port: '443'
  server: 198.62.62.64
  servername: lm.ylks.us.kg
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lm.ylks.us.kg
    path: /?ed=2560
- name: å¾·å›½-3
  network: ws
  port: '443'
  server: 185.103.253.35
  servername: lm.ylks.us.kg
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lm.ylks.us.kg
    path: /?ed=2560
- name: ç‘å…¸-3
  password: telegram-id-privatevpns
  port: '22222'
  server: 16.170.174.167
  sni: trojan.burgerip.co.uk
  type: trojan
- name: çˆ±å°”å…°-3
  password: telegram-id-directvpn
  port: '22222'
  server: 18.200.6.189
  sni: trojan.burgerip.co.uk
  type: trojan
- name: éŸ©å›½-13
  password: 36146310-e7fc-443f-864c-4fe46b92c35f
  port: '12053'
  server: cn2.cdn.xfltd-cdn.top
  skip-cert-verify: true
  sni: cdn.alibaba.com
  type: trojan
- cipher: aes-256-cfb
  name: ä¸­å›½-9
  password: JN8psKoncqaqS4ul
  port: '22064'
  server: 221.181.185.71
  type: ss
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: é»˜è®¤ä»£ç†
  proxies:
  - 'è‡ªåŠ¨é€‰æ‹©: 63ä¸ª'
  - 'æ‰‹åŠ¨é€‰æ‹©: 63ä¸ª'
  - 'æ—¥æœ¬åˆ†åŒº: 5ä¸ª'
  - 'æ–°åŠ å¡åˆ†åŒº: 3ä¸ª'
  - 'éŸ©å›½åˆ†åŒº: 13ä¸ª'
  - 'ä¸­å›½åˆ†åŒº: 9ä¸ª'
  - 'è‹±å›½åˆ†åŒº: 6ä¸ª'
  - 'æ³•å›½åˆ†åŒº: 3ä¸ª'
  - 'ç¾å›½åˆ†åŒº: 15ä¸ª'
  - 'å¾·å›½åˆ†åŒº: 3ä¸ª'
  - 'çˆ±å°”å…°åˆ†åŒº: 3ä¸ª'
  - 'ç‘å…¸åˆ†åŒº: 3ä¸ª'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©: 63ä¸ª'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: 'æ‰‹åŠ¨é€‰æ‹©: 63ä¸ª'
  type: select
- filter: (?i)æ—¥æœ¬|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ—¥æœ¬åˆ†åŒº: 5ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ–°åŠ å¡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ–°åŠ å¡åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)éŸ©å›½|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'éŸ©å›½åˆ†åŒº: 13ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ä¸­å›½|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ä¸­å›½åˆ†åŒº: 9ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)è‹±å›½|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‹±å›½åˆ†åŒº: 6ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ³•å›½|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ³•å›½åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç¾å›½|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç¾å›½åˆ†åŒº: 15ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)å¾·å›½|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'å¾·å›½åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)çˆ±å°”å…°|IE|ie
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ie.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'çˆ±å°”å…°åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç‘å…¸|SE|se
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/se.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç‘å…¸åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,é»˜è®¤ä»£ç†
- GEOSITE,microsoft,DIRECT
- GEOIP,google,é»˜è®¤ä»£ç†
- GEOIP,telegram,é»˜è®¤ä»£ç†
- GEOIP,twitter,é»˜è®¤ä»£ç†
- GEOIP,CN,DIRECT,no-resolve
- MATCH,é»˜è®¤ä»£ç†
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
