allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-256-cfb
  name: æ—¥æœ¬-1
  password: amazonskr05
  port: '443'
  server: 13.113.17.246
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-1
  password: amazonskr05
  port: '443'
  server: 13.229.98.87
  type: ss
- country: ğŸ ZZ
  delay: '269'
  name: é¦™æ¸¯-1
  password: 1a8050cd-50d8-4b7d-a73e-193222f39822
  port: '27102'
  server: aafrtpfxr.hkl02i9zjfegelp.5xfsur8v62.gosdk.xyz
  skip-cert-verify: true
  type: trojan
  udp: true
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-2
  password: amazonskr05
  port: '443'
  server: 47.129.244.12
  type: ss
- client-fingerprint: chrome
  mptcp: true
  name: ç¾å›½-1
  network: ws
  packet-encoding: xudp
  port: '10086'
  server: 142.147.94.108
  servername: akilelaxub.eessgrgrgrgr.cloudns.nz
  skip-cert-verify: false
  smux:
    enabled: true
    max-streams: '10'
    padding: true
    protocol: h2mux
  tfo: true
  tls: true
  type: vless
  udp: true
  uuid: 2fa6651f-7067-4e5c-a944-f0836d239efd
  ws-opts:
    headers:
      Host: akilelaxub.eessgrgrgrgr.cloudns.nz
    path: /buefubwuefuwefuwffewf
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true
- cipher: aes-256-cfb
  name: æ—¥æœ¬-2
  password: amazonskr05
  port: '443'
  server: 3.112.215.69
  type: ss
- cipher: aes-128-gcm
  name: æ—¥æœ¬-3
  password: shadowsocks
  port: '443'
  server: 149.22.87.240
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-3
  password: amazonskr05
  port: '443'
  server: 13.250.3.43
  type: ss
- client-fingerprint: chrome
  mptcp: true
  name: ç¾å›½-2
  network: ws
  packet-encoding: xudp
  port: '37049'
  server: 142.147.94.159
  servername: akilelaxub.eessgrgrgrgr.cloudns.nz
  skip-cert-verify: false
  smux:
    enabled: true
    max-streams: '10'
    padding: true
    protocol: h2mux
  tfo: true
  tls: true
  type: vless
  udp: true
  uuid: 2fa6651f-7067-4e5c-a944-f0836d239efd
  ws-opts:
    headers:
      Host: akilelaxub.eessgrgrgrgr.cloudns.nz
    path: /buefubwuefuwefuwffewf
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-4
  password: amazonskr05
  port: '443'
  server: 13.215.205.186
  type: ss
- cipher: rc4-md5
  name: ä¸­å›½-1
  obfs: plain
  obfs-param: 8195986416.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: '40219'
  protocol: auth_aes128_md5
  protocol-param: 86416:SlZFuy
  server: 7438974b54cf5c57.cdn.jiashule.com
  type: ssr
- cipher: rc4-md5
  name: ä¸­å›½-2
  obfs: plain
  obfs-param: cd5ed74592.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: '40257'
  protocol: auth_aes128_md5
  protocol-param: 74592:o4fbeopsgcf
  server: 28b09af269781f9b.cdn.jiashule.com
  type: ssr
- cipher: aes-256-cfb
  name: ç¾å›½-3
  password: amazonskr05
  port: '443'
  server: 34.209.103.254
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-5
  password: amazonskr05
  port: '443'
  server: 54.169.139.18
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-4
  password: amazonskr05
  port: '443'
  server: 18.246.235.247
  type: ss
- cipher: aes-256-cfb
  delay: '777'
  name: ç¾å›½-5
  password: amazonskr05
  port: '443'
  server: 44.243.115.246
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-6
  password: amazonskr05
  port: '443'
  server: 54.213.247.125
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-1
  password: qwerREWQ@@
  port: '54345'
  server: 221.139.79.57
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-6
  password: amazonskr05
  port: '443'
  server: 54.169.135.226
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-7
  password: amazonskr05
  port: '443'
  server: 54.71.237.242
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-8
  password: amazonskr05
  port: '443'
  server: 54.185.199.99
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-9
  password: amazonskr05
  port: '443'
  server: 34.210.94.67
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-10
  password: amazonskr05
  port: '443'
  server: 35.94.16.186
  type: ss
- name: æ³•å›½-1
  password: telegram-id-privatevpns
  port: '22222'
  server: 13.39.117.64
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: aes-128-gcm
  name: ç¾å›½-11
  password: shadowsocks
  port: '443'
  server: 156.146.38.168
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-12
  password: amazonskr05
  port: '443'
  server: 35.87.185.248
  type: ss
- name: è‹±å›½-1
  password: telegram-id-privatevpns
  port: '22222'
  server: 35.177.252.131
  sni: trojan.burgerip.co.uk
  type: trojan
- name: ç¾å›½-13
  network: ws
  port: '443'
  server: 141.101.121.254
  servername: az.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      Host: az.ylks.xyz
    path: /?ed=2048
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-14
  password: uz*q6N5=kB
  port: '25486'
  server: 150.241.95.62
  type: ss
- alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: ç¾å›½-15
  network: ws
  port: '443'
  server: 199.232.5.101
  servername: mefa.ir
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: mefa.ir
    path: /H?ed=2560
- client-fingerprint: chrome
  delay: '884'
  name: ç¾å›½-16
  network: ws
  port: '443'
  server: 199.232.5.79
  servername: mefa.ir
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: mefa.ir
    path: /H?ed=2560
- cipher: chacha20-ietf-poly1305
  name: èŠ¬å…°-1
  password: X7eoEBrARWsBUiVfchVEdH
  port: '443'
  server: 185.77.217.121
  type: ss
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: é»˜è®¤ä»£ç†
  proxies:
  - 'è‡ªåŠ¨é€‰æ‹©: 32ä¸ª'
  - 'æ‰‹åŠ¨é€‰æ‹©: 32ä¸ª'
  - 'æ—¥æœ¬åˆ†åŒº: 3ä¸ª'
  - 'æ–°åŠ å¡åˆ†åŒº: 6ä¸ª'
  - 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  - 'ç¾å›½åˆ†åŒº: 16ä¸ª'
  - 'ä¸­å›½åˆ†åŒº: 2ä¸ª'
  - 'éŸ©å›½åˆ†åŒº: 1ä¸ª'
  - 'æ³•å›½åˆ†åŒº: 1ä¸ª'
  - 'è‹±å›½åˆ†åŒº: 1ä¸ª'
  - 'èŠ¬å…°åˆ†åŒº: 1ä¸ª'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©: 32ä¸ª'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: 'æ‰‹åŠ¨é€‰æ‹©: 32ä¸ª'
  type: select
- filter: (?i)æ—¥æœ¬|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ—¥æœ¬åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ–°åŠ å¡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ–°åŠ å¡åˆ†åŒº: 6ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)é¦™æ¸¯|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç¾å›½|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç¾å›½åˆ†åŒº: 16ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ä¸­å›½|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ä¸­å›½åˆ†åŒº: 2ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)éŸ©å›½|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'éŸ©å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ³•å›½|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ³•å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)è‹±å›½|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‹±å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)èŠ¬å…°|FI|fi
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fi.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'èŠ¬å…°åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,é»˜è®¤ä»£ç†
- GEOSITE,microsoft,DIRECT
- GEOIP,google,é»˜è®¤ä»£ç†
- GEOIP,telegram,é»˜è®¤ä»£ç†
- GEOIP,twitter,é»˜è®¤ä»£ç†
- GEOIP,CN,DIRECT,no-resolve
- MATCH,é»˜è®¤ä»£ç†
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
