allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-1
  password: 54f4e2f4-f0e1-4a15-a0cf-3a3234ab58fb
  port: '11001'
  server: 183.232.229.165
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-1
  password: amazonskr05
  port: '443'
  server: 54.249.192.248
  type: ss
- delay: '527'
  name: ä¸­å›½-2
  port: '7890'
  server: 182.92.216.171
  skip-cert-verify: true
  tls: false
  type: http
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ—¥æœ¬-2
  password: amazonskr05
  port: '443'
  server: 54.238.227.113
  tfo: false
  type: ss
- cipher: aes-256-cfb
  country: ğŸ‡¸ğŸ‡¬SG
  delay: '288'
  name: æ–°åŠ å¡-1
  password: amazonskr05
  port: '443'
  server: 54.254.23.34
  type: ss
- cipher: aes-256-cfb
  name: ä¸­å›½-3
  password: 75ly0yJ90LP5Ural
  port: '20705'
  server: 221.181.185.71
  type: ss
- cipher: aes-256-cfb
  name: æ–°åŠ å¡-2
  password: amazonskr05
  port: '443'
  server: 13.229.212.209
  type: ss
- name: æ—¥æœ¬-3
  network: tcp
  password: 2aa1581d-bfc9-4d3a-84f3-742674fb5d3a
  port: '20230'
  server: jp005.421421.xyz
  skip-cert-verify: true
  sni: 421421.xyz
  type: trojan
  udp: true
- cipher: aes-256-cfb
  name: æ—¥æœ¬-4
  password: amazonskr05
  port: '443'
  server: 13.114.140.218
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-5
  password: amazonskr05
  port: '443'
  server: 13.115.189.201
  type: ss
- cipher: aes-128-gcm
  client-fingerprint: chrome
  name: è‹±å›½-1
  password: shadowsocks
  port: '443'
  server: 212.102.53.198
  tfo: false
  type: ss
- name: æ—¥æœ¬-6
  network: tcp
  password: 2aa1581d-bfc9-4d3a-84f3-742674fb5d3a
  port: '20230'
  server: jp006.421421.xyz
  skip-cert-verify: true
  sni: 421421.xyz
  type: trojan
  udp: true
- name: é¦™æ¸¯-1
  network: ws
  port: '443'
  server: 103.220.72.40
  servername: dr.ylks.xyz
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: dr.ylks.xyz
    path: /blue
- cipher: aes-256-cfb
  name: éŸ©å›½-1
  password: amazonskr05
  port: '443'
  server: 3.38.253.126
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-4
  password: 5409bf78-b122-4b9b-9050-da36576f5bbc
  port: '25991'
  server: tg_mfbpn03.52cloud.us.kg
  type: ss
- cipher: chacha20-ietf-poly1305
  name: è‹±å›½-2
  password: mps3FwmDjLrWaOVg
  port: '443'
  server: 3.11.194.30
  type: ss
- cipher: aes-256-cfb
  client-fingerprint: chrome
  name: æ–°åŠ å¡-3
  password: amazonskr05
  port: '443'
  server: 13.229.57.182
  tfo: false
  type: ss
- cipher: aes-256-cfb
  name: ä¸­å›½-5
  password: f52SZksXnGNfc72Q
  port: '23382'
  server: 221.181.185.71
  type: ss
- name: å°æ¹¾-1
  network: ws
  port: '81'
  server: 210.61.97.241
  servername: lr.ylka.us.kg
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lr.ylka.us.kg
    path: /?ed=2560
- cipher: aes-256-cfb
  name: éŸ©å›½-2
  password: amazonskr05
  port: '443'
  server: 3.35.222.240
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-1
  password: amazonskr05
  port: '443'
  server: 35.94.175.12
  type: ss
- client-fingerprint: chrome
  delay: '1296'
  flow: xtls-rprx-vision
  name: éŸ©å›½-3
  network: tcp
  port: '443'
  reality-opts:
    public-key: t_MDb0CgA1ZwyIj7NpJ2hvp85C9sH8Nsnd8etE8NKw4
  server: 140.238.18.228
  servername: updates.cdn-apple.com
  tls: true
  type: vless
  udp: true
  uuid: 2353e75d-7cec-4e7f-9eae-e996117cac04
- cipher: aes-256-gcm
  name: ç¾å›½-2
  password: g5MeD6Ft3CWlJId
  port: '5003'
  server: 23.157.40.89
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-6
  password: 5409bf78-b122-4b9b-9050-da36576f5bbc
  port: '53935'
  server: tg_mfbpn03.52cloud.us.kg
  type: ss
- cipher: aes-128-gcm
  name: è‹±å›½-3
  password: shadowsocks
  port: '443'
  server: 212.102.53.195
  type: ss
  udp: true
- name: éŸ©å›½-4
  network: ws
  port: '37498'
  server: 221.161.207.216
  servername: lr.kpcloud.eu.org
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lr.kpcloud.eu.org
    path: /blue
- cipher: aes-256-gcm
  name: ç¾å›½-3
  password: TEzjfAYq2IjtuoS
  port: '6697'
  server: 69.50.95.218
  type: ss
- name: å¾·å›½-1
  password: telegram-id-privatevpns
  port: '22222'
  server: 3.76.25.56
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: aes-256-gcm
  name: ç¾å›½-4
  password: Y6R9pAtvxxzmGC
  port: '5000'
  server: 23.157.40.89
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-7
  password: amazonskr05
  port: '443'
  server: 18.183.186.69
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-5
  password: KixLvKzwjekG00rm
  port: '8080'
  server: 38.75.136.33
  type: ss
- cipher: aes-256-cfb
  name: ä¸­å›½-7
  password: bbO8KazkNBUGb7HP
  port: '20934'
  server: 221.181.185.71
  type: ss
- cipher: aes-256-cfb
  name: éŸ©å›½-5
  password: amazonskr05
  port: '443'
  server: 52.78.193.3
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-6
  password: amazonskr05
  port: '443'
  server: 35.87.156.159
  type: ss
- name: éŸ©å›½-6
  network: ws
  port: '12273'
  server: 211.228.180.147
  servername: dr.ylks.xyz
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: dr.ylks.xyz
    path: /blue
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-8
  password: 68a1de21-c639-47c7-9e3c-4dc8a0b14e9f
  port: '35853'
  server: uslow.papermsg.top
  type: ss
- name: è‹±å›½-4
  password: telegram-id-privatevpns
  port: '22222'
  server: 18.171.72.123
  sni: trojan.burgerip.co.uk
  type: trojan
- name: æ³•å›½-1
  password: telegram-id-privatevpns
  port: '22222'
  server: 52.47.57.120
  skip-cert-verify: true
  sni: trojan.burgerip.co.uk
  type: trojan
- name: è‹±å›½-5
  password: telegram-id-privatevpns
  port: '22222'
  server: 3.10.106.215
  sni: trojan.burgerip.co.uk
  type: trojan
- cipher: aes-256-cfb
  name: ç¾å›½-7
  password: amazonskr05
  port: '443'
  server: 18.236.95.86
  type: ss
- name: å¾·å›½-2
  network: ws
  port: '443'
  server: 185.103.253.35
  servername: lr.ylks.us.kg
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lr.ylks.us.kg
    path: /?ed=2560
- name: éŸ©å›½-7
  network: ws
  port: '10255'
  server: 175.206.2.186
  servername: lr.kpcloud.eu.org
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lr.kpcloud.eu.org
    path: /blue
- name: éŸ©å›½-8
  network: ws
  port: '18050'
  server: 119.195.219.150
  servername: ar.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      host: ar.ylks.xyz
    path: /?proxyip=proxyir.kr.fxxr.dedyr.io
- cipher: aes-256-cfb
  name: ä¸­å›½-9
  password: JN8psKoncqaqS4ul
  port: '22064'
  server: 221.181.185.71
  type: ss
- name: éŸ©å›½-9
  network: ws
  port: '32900'
  server: 146.56.151.254
  servername: lr.kpcloud.eu.org
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lr.kpcloud.eu.org
    path: /blue
- name: ä¸­å›½-10
  password: 8d4a8689-e8fd-4405-9834-3f812c528db0
  port: '13036'
  server: naiu-other.05vr9nyqg5.download
  sni: cloudflare.node-ssl.cdn-alibaba.com
  type: trojan
- name: ç¾å›½-8
  network: ws
  port: '443'
  server: 192.9.157.76
  servername: ar.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      host: ar.ylks.xyz
    path: /?ed=2048
- cipher: aes-256-gcm
  name: ç¾å›½-9
  password: g5MeD6Ft3CWlJId
  port: '5004'
  server: 23.157.40.89
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-10
  password: pKEW8JPByTVTLtM
  port: '443'
  server: 23.157.40.89
  type: ss
- name: ç¾å›½-11
  network: ws
  port: '443'
  server: 43.153.103.203
  servername: dr.ylks.xyz
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: dr.ylks.xyz
    path: /blue
- delay: '898'
  name: ç¾å›½-12
  network: ws
  port: '80'
  server: 199.232.37.15
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560
- cipher: aes-256-gcm
  name: ç¾å›½-13
  password: Y6R9pAtvxxzmGC
  port: '5600'
  server: 38.75.136.33
  type: ss
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: é»˜è®¤ä»£ç†
  proxies:
  - 'è‡ªåŠ¨é€‰æ‹©: 52ä¸ª'
  - 'æ‰‹åŠ¨é€‰æ‹©: 52ä¸ª'
  - 'ä¸­å›½åˆ†åŒº: 10ä¸ª'
  - 'æ—¥æœ¬åˆ†åŒº: 7ä¸ª'
  - 'æ–°åŠ å¡åˆ†åŒº: 3ä¸ª'
  - 'è‹±å›½åˆ†åŒº: 5ä¸ª'
  - 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  - 'éŸ©å›½åˆ†åŒº: 9ä¸ª'
  - 'å°æ¹¾åˆ†åŒº: 1ä¸ª'
  - 'ç¾å›½åˆ†åŒº: 13ä¸ª'
  - 'å¾·å›½åˆ†åŒº: 2ä¸ª'
  - 'æ³•å›½åˆ†åŒº: 1ä¸ª'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©: 52ä¸ª'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: 'æ‰‹åŠ¨é€‰æ‹©: 52ä¸ª'
  type: select
- filter: (?i)ä¸­å›½|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ä¸­å›½åˆ†åŒº: 10ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ—¥æœ¬|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ—¥æœ¬åˆ†åŒº: 7ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ–°åŠ å¡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ–°åŠ å¡åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)è‹±å›½|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‹±å›½åˆ†åŒº: 5ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)é¦™æ¸¯|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'é¦™æ¸¯åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)éŸ©å›½|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'éŸ©å›½åˆ†åŒº: 9ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)å°æ¹¾|TW|tw
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tw.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'å°æ¹¾åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç¾å›½|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç¾å›½åˆ†åŒº: 13ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)å¾·å›½|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'å¾·å›½åˆ†åŒº: 2ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ³•å›½|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ³•å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,é»˜è®¤ä»£ç†
- GEOSITE,microsoft,DIRECT
- GEOIP,google,é»˜è®¤ä»£ç†
- GEOIP,telegram,é»˜è®¤ä»£ç†
- GEOIP,twitter,é»˜è®¤ä»£ç†
- GEOIP,CN,DIRECT,no-resolve
- MATCH,é»˜è®¤ä»£ç†
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
