allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-256-cfb
  delay: '272'
  name: æ—¥æœ¬-1
  password: amazonskr05
  port: '443'
  server: 3.112.45.212
  type: ss
- cipher: aes-256-cfb
  name: æ—¥æœ¬-2
  password: amazonskr05
  port: '443'
  server: 54.249.192.248
  type: ss
- cipher: aes-256-cfb
  name: ä¸­å›½-1
  password: 75ly0yJ90LP5Ural
  port: '20705'
  server: 221.181.185.71
  type: ss
- name: ä¸­å›½-2
  network: tcp
  password: wwTIozXY
  port: '27131'
  server: 36.151.192.201
  skip-cert-verify: true
  type: trojan
  udp: true
- cipher: aes-256-cfb
  name: æ—¥æœ¬-3
  password: amazonskr05
  port: '443'
  server: 13.231.124.247
  type: ss
- cipher: aes-128-gcm
  name: è‹±å›½-1
  password: shadowsocks
  port: '443'
  server: 212.102.53.198
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: éŸ©å›½-1
  password: amazonskr05
  port: '443'
  server: 3.38.253.126
  type: ss
- name: ä¸­å›½-3
  network: tcp
  password: d6d86a97-2bef-4f89-9527-ce2003377677
  port: '13007'
  server: naiu-hk.05vr9nyqg5.download
  skip-cert-verify: true
  sni: naiu-hk.05vr9nyqg5.download
  type: trojan
  udp: true
- cipher: aes-256-cfb
  name: æ—¥æœ¬-4
  password: amazonskr05
  port: '443'
  server: 13.114.140.218
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-1
  password: Í„mÍ’ßMÖ¡TyÛ™Ò«1Í›PÌ
  port: '20002'
  server: 67.220.72.41
  type: ss
- cipher: aes-256-cfb
  name: ç¾å›½-2
  password: amazonskr05
  port: '443'
  server: 18.236.95.86
  type: ss
- cipher: aes-256-cfb
  country: ğŸ‡ºğŸ‡¸US
  delay: '607'
  name: ç¾å›½-3
  password: amazonskr05
  port: '443'
  server: 35.86.117.124
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ç¾å›½-4
  password: Í„mÍ’ßMÖ¡TyÛ™Ò«1Í›PÌ
  port: '20002'
  server: mynode.work.gd
  type: ss
- name: å¾·å›½-1
  password: telegram-id-directvpn
  port: '22222'
  server: 63.176.31.124
  sni: trojan.burgerip.co.uk
  type: trojan
- name: éŸ©å›½-2
  network: ws
  port: '12273'
  server: 211.228.180.147
  servername: dr.ylks.xyz
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      Host: dr.ylks.xyz
    path: /blue
- name: éŸ©å›½-3
  network: ws
  port: '18050'
  server: 119.195.219.150
  servername: ar.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      Host: ar.ylks.xyz
    path: /?proxyip=proxyir.kr.fxxr.dedyr.io
- cipher: aes-256-cfb
  name: ç¾å›½-5
  password: amazonskr05
  port: '443'
  server: 54.185.199.99
  type: ss
- name: ç¾å›½-6
  network: ws
  port: '443'
  server: 104.19.34.54
  servername: lt.ylks.us.kg
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lt.ylks.us.kg
    path: /?ed=2560
- name: è‹±å›½-2
  password: telegram-id-privatevpns
  port: '22222'
  server: 13.42.174.68
  sni: trojan.burgerip.co.uk
  type: trojan
- name: æ³•å›½-1
  password: telegram-id-privatevpns
  port: '22222'
  server: 35.181.17.166
  sni: trojan.burgerip.co.uk
  type: trojan
- name: è‹±å›½-3
  password: telegram-id-privatevpns
  port: '22222'
  server: 3.10.248.98
  sni: trojan.burgerip.co.uk
  type: trojan
- name: æ³•å›½-2
  password: telegram-id-privatevpns
  port: '22222'
  server: 13.37.47.4
  sni: trojan.burgerip.co.uk
  type: trojan
- name: çˆ±å°”å…°-1
  password: telegram-id-directvpn
  port: '22222'
  server: 52.212.213.42
  sni: trojan.burgerip.co.uk
  type: trojan
- name: ç‘å…¸-1
  password: telegram-id-directvpn
  port: '22222'
  server: 13.50.73.187
  sni: trojan.burgerip.co.uk
  type: trojan
- delay: '1117'
  name: ç¾å›½-7
  network: ws
  port: '80'
  server: 151.101.3.10
  type: vless
  udp: true
  uuid: cefffd1d-cc58-4560-b4d1-44f1af528f30
  ws-opts:
    headers:
      Host: uni.fi
    path: /?ed=2048
- name: æ³•å›½-3
  password: telegram-id-privatevpns
  port: '22222'
  server: 15.237.161.156
  sni: trojan.burgerip.co.uk
  type: trojan
- name: æ³•å›½-4
  password: telegram-id-directvpn
  port: '22222'
  server: 13.37.9.30
  sni: trojan.burgerip.co.uk
  type: trojan
- name: ç¾å›½-8
  network: ws
  port: '443'
  server: 104.19.49.117
  servername: lt.ylka.us.kg
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lt.ylka.us.kg
    path: /?ed=2560
- cipher: aes-256-cfb
  name: ä¸­å›½-4
  password: UomcSobsfu2SwwCn
  port: '23278'
  server: 221.181.185.71
  type: ss
- name: éŸ©å›½-4
  network: ws
  port: '443'
  server: 152.70.249.67
  servername: ar.ylks.xyz
  tls: true
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
  ws-opts:
    headers:
      Host: ar.ylks.xyz
    path: /?ed=2048
- cipher: aes-256-gcm
  name: ç¾å›½-9
  password: PCnnH6SQSnfoS27
  port: '8091'
  server: 169.197.141.84
  type: ss
- cipher: aes-256-gcm
  name: ç¾å›½-10
  password: pKEW8JPByTVTLtM
  port: '443'
  server: 169.197.141.84
  type: ss
- delay: '898'
  name: ç¾å›½-11
  network: ws
  port: '80'
  server: 199.232.37.15
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560
- cipher: chacha20-ietf-poly1305
  name: ä¸­å›½-5
  password: 68a1de21-c639-47c7-9e3c-4dc8a0b14e9f
  port: '35853'
  server: uslow.papermsg.top
  type: ss
- name: ç¾å›½-12
  network: ws
  port: '443'
  server: 104.19.40.134
  servername: lt.kpcloud.eu.org
  tls: true
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
  ws-opts:
    headers:
      host: lt.kpcloud.eu.org
    path: /blue
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: é»˜è®¤ä»£ç†
  proxies:
  - 'è‡ªåŠ¨é€‰æ‹©: 35ä¸ª'
  - 'æ‰‹åŠ¨é€‰æ‹©: 35ä¸ª'
  - 'æ—¥æœ¬åˆ†åŒº: 4ä¸ª'
  - 'ä¸­å›½åˆ†åŒº: 5ä¸ª'
  - 'è‹±å›½åˆ†åŒº: 3ä¸ª'
  - 'éŸ©å›½åˆ†åŒº: 4ä¸ª'
  - 'ç¾å›½åˆ†åŒº: 12ä¸ª'
  - 'å¾·å›½åˆ†åŒº: 1ä¸ª'
  - 'æ³•å›½åˆ†åŒº: 4ä¸ª'
  - 'çˆ±å°”å…°åˆ†åŒº: 1ä¸ª'
  - 'ç‘å…¸åˆ†åŒº: 1ä¸ª'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‡ªåŠ¨é€‰æ‹©: 35ä¸ª'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: 'æ‰‹åŠ¨é€‰æ‹©: 35ä¸ª'
  type: select
- filter: (?i)æ—¥æœ¬|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ—¥æœ¬åˆ†åŒº: 4ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ä¸­å›½|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ä¸­å›½åˆ†åŒº: 5ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)è‹±å›½|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'è‹±å›½åˆ†åŒº: 3ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)éŸ©å›½|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'éŸ©å›½åˆ†åŒº: 4ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç¾å›½|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç¾å›½åˆ†åŒº: 12ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)å¾·å›½|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'å¾·å›½åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)æ³•å›½|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'æ³•å›½åˆ†åŒº: 4ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)çˆ±å°”å…°|IE|ie
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ie.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'çˆ±å°”å…°åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)ç‘å…¸|SE|se
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/se.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: 'ç‘å…¸åˆ†åŒº: 1ä¸ª'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,é»˜è®¤ä»£ç†
- GEOSITE,microsoft,DIRECT
- GEOIP,google,é»˜è®¤ä»£ç†
- GEOIP,telegram,é»˜è®¤ä»£ç†
- GEOIP,twitter,é»˜è®¤ä»£ç†
- GEOIP,CN,DIRECT,no-resolve
- MATCH,é»˜è®¤ä»£ç†
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
